import { JobListing } from '../types';

const sampleJobs: JobListing[] = [
  // USA
  {
    id: '1',
    title: 'Senior Frontend Engineer',
    company: 'Innovatech',
    location: 'San Francisco, California, USA',
    salaryMin: 150000,
    salaryMax: 180000,
    description: 'Join our team to build next-generation user interfaces with React and TypeScript. You will be responsible for developing and maintaining web applications, and collaborating with our design and backend teams.',
    url: '#',
  },
  {
    id: '2',
    title: 'Backend Developer (Python/Django)',
    company: 'DataSolutions',
    location: 'New York, New York, USA',
    salaryMin: 140000,
    salaryMax: 170000,
    description: 'We are looking for a Python developer to work on our data processing pipeline. Experience with Django, REST APIs, and PostgreSQL is required.',
    url: '#',
  },
  {
    id: '4',
    title: 'UX/UI Designer',
    company: 'CreativeMinds',
    location: 'Austin, Texas, USA',
    salaryMin: 90000,
    salaryMax: 110000,
    description: 'Design intuitive and beautiful user experiences for our mobile and web applications. A strong portfolio is required.',
    url: '#',
  },
  {
    id: '5',
    title: 'Data Scientist',
    company: 'QuantumLeap AI',
    location: 'Boston, Massachusetts, USA',
    salaryMin: 160000,
    salaryMax: 200000,
    description: 'Analyze large datasets to extract meaningful insights and build predictive models. PhD or MS in a quantitative field preferred.',
    url: '#',
  },
  {
    id: '6',
    title: 'DevOps Engineer',
    company: 'CloudNine',
    location: 'Seattle, Washington, USA',
    salaryMin: 145000,
    salaryMax: 175000,
    description: 'Manage our cloud infrastructure on AWS, automate deployments, and ensure system reliability and scalability. Experience with Kubernetes and Terraform is a must.',
    url: '#',
  },
  {
    id: '7',
    title: 'Product Manager',
    company: 'Innovatech',
    location: 'San Francisco, California, USA',
    salaryMin: 155000,
    salaryMax: 190000,
    description: 'Define product vision, strategy, and roadmap. Work closely with engineering, design, and marketing to launch new features.',
    url: '#',
  },
    {
    id: '10',
    title: 'Cloud Security Engineer',
    company: 'SecureNet',
    location: 'Washington, D.C., USA',
    salaryMin: 150000,
    salaryMax: 185000,
    description: 'Protect our cloud environments from threats. Implement security best practices and respond to incidents.',
    url: '#',
  },
   {
    id: '14',
    title: 'Marketing Manager',
    company: 'CreativeMinds',
    location: 'Austin, Texas, USA',
    salaryMin: 110000,
    salaryMax: 140000,
    description: 'Lead our marketing campaigns and strategy. MBA preferred.',
    url: '#',
  },
  {
    id: '15',
    title: 'Business Analyst',
    company: 'DataSolutions',
    location: 'New York, New York, USA',
    salaryMin: 90000,
    salaryMax: 120000,
    description: 'Analyze business processes and identify opportunities for improvement. Strong analytical and communication skills required.',
    url: '#',
  },
  // Remote
  {
    id: '3',
    title: 'Full-Stack Engineer',
    company: 'Innovatech',
    location: 'Remote, N/A, N/A',
    salaryMin: 130000,
    salaryMax: 160000,
    description: 'Work on both frontend and backend parts of our platform. Tech stack includes React, Node.js, and MongoDB.',
    url: '#',
  },
   {
    id: '8',
    title: 'Junior React Developer',
    company: 'StartupHub',
    location: 'Remote, N/A, N/A',
    salaryMin: 80000,
    salaryMax: 100000,
    description: 'An exciting opportunity for a junior developer to grow their skills in a fast-paced environment. You will be working with React and modern frontend technologies.',
    url: '#',
  },
  // Canada
  {
    id: '16',
    title: 'AI/ML Engineer',
    company: 'Maple AI',
    location: 'Toronto, Ontario, Canada',
    salaryMin: 120000,
    salaryMax: 150000,
    description: 'Develop and deploy machine learning models. Experience with TensorFlow and PyTorch is essential.',
    url: '#',
  },
  {
    id: '17',
    title: 'Full-Stack Engineer',
    company: 'Maple AI',
    location: 'Vancouver, British Columbia, Canada',
    salaryMin: 110000,
    salaryMax: 140000,
    description: 'Join our dynamic team building a cutting-edge web application using Node.js and Vue.js.',
    url: '#',
  },
  // UK
  {
    id: '18',
    title: 'Senior Backend Engineer',
    company: 'FinTech UK',
    location: 'London, England, United Kingdom',
    salaryMin: 75000,
    salaryMax: 90000,
    description: 'Backend development for a leading financial technology company. Java or Kotlin experience required.',
    url: '#',
  },
  {
    id: '19',
    title: 'Data Analyst',
    company: 'HealthData Corp',
    location: 'Manchester, England, United Kingdom',
    salaryMin: 45000,
    salaryMax: 60000,
    description: 'Analyzing healthcare data to provide insights. SQL and Power BI skills are a must.',
    url: '#',
  },
  // Germany
  {
    id: '20',
    title: 'Embedded Systems Engineer',
    company: 'AutoTech GmbH',
    location: 'Munich, Bavaria, Germany',
    salaryMin: 80000,
    salaryMax: 100000,
    description: 'Develop embedded software for automotive systems. C/C++ experience is critical.',
    url: '#',
  },
  {
    id: '21',
    title: 'Product Manager',
    company: 'E-Commerce Berlin',
    location: 'Berlin, Berlin, Germany',
    salaryMin: 85000,
    salaryMax: 110000,
    description: 'Lead product development for our online marketplace.',
    url: '#',
  },
  // India
  {
    id: '22',
    title: 'Software Development Engineer',
    company: 'Tech India',
    location: 'Bangalore, Karnataka, India',
    salaryMin: 1800000,
    salaryMax: 2500000,
    description: 'SDE-II role for a large-scale e-commerce platform. Strong problem-solving skills required.',
    url: '#',
  },
  {
    id: '23',
    title: 'DevOps Engineer',
    company: 'InfraCloud IN',
    location: 'Pune, Maharashtra, India',
    salaryMin: 1500000,
    salaryMax: 2200000,
    description: 'Manage and scale our multi-cloud infrastructure.',
    url: '#',
  },
  // Australia
  {
    id: '24',
    title: 'Senior Frontend Engineer',
    company: 'Aussie Web Solutions',
    location: 'Sydney, New South Wales, Australia',
    salaryMin: 130000,
    salaryMax: 160000,
    description: 'Lead frontend projects using React and GraphQL.',
    url: '#',
  },
  {
    id: '25',
    title: 'Cyber Security Analyst',
    company: 'CyberSafe AU',
    location: 'Melbourne, Victoria, Australia',
    salaryMin: 110000,
    salaryMax: 140000,
    description: 'Monitor and protect our systems from cyber threats.',
    url: '#',
  }
];


export const jobService = {
  fetchJobs: (): Promise<JobListing[]> => {
    return new Promise(resolve => {
      setTimeout(() => {
        resolve(sampleJobs);
      }, 1000); // Simulate network delay
    });
  },
};